[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"


[[bin]]
name="23_1_1"
path="./src/23/1/part1.rs"


[[bin]]
name="23_1_2"
path="./src/23/1/part2.rs"

